### ISSUE TITLE
Requisito Funcional 11 ambiguo y poco preciso.

### ISSUE THREAD

**Issue by dari1495** [Belberus/notas-vv#1]
El requisito funcional 11 es ambiguo y poco preciso y claro.

**Comment by Belberus** [comment]
La ambigüedad fue resuelta durante la implementación, por lo que no generó problemas adicionales.

**Comment by miguel-latre** [comment]
A partir de la descripción del _issue_ y del informe de evaluación estática, poco se puede decir sobre qué problemas presentaba el RF11. En todo caso, pese a que la ambigüedad fuera resuelta durante la implementación, si se ha detectado un problema, se debería haber vuelto a redactar el requisito incluyendo lo que se interpretó durante la implementación.

**Comment by Belberus** [comment]
La ambigüedad se ha resuelto y se han modificado los documentos "Plan de pruebas maestro" e "Informe final de pruebas" para que reflejen el requisito corregido.
