### ISSUE TITLE
Requisito Funcional 12 ambiguo y poco preciso

### ISSUE THREAD

**Issue by dari1495** [Belberus/notas-vv#2]
Lo mismo que el anterior, falta claridad.

**Comment by Belberus** [comment]
La ambigüedad fue resuelta durante la implementación, por lo que no generó problemas adicionales.

**Comment by miguel-latre** [comment]
Lo mismo que con el _issue_  #1 : A partir de la descripción del _issue_ y del informe de evaluación estática, poco se puede decir sobre qué problemas presentaba el RF12. En todo caso, pese a que la ambigüedad fuera resuelta durante la implementación, si se ha detectado un problema, se debería haber vuelto a redactar el requisito incluyendo lo que se interpretó durante la implementación.
En el trabajo, informáis de problemas con los requisitos RF10 y RF11, mientras que aquí habéis abierto _issues_ para los RF11 y RF12.

**Comment by Belberus** [comment]
La ambigüedad se ha resuelto y se han modificado los documentos "Plan de pruebas maestro" e "Informe final de pruebas" para que reflejen el requisito corregido.
