### ISSUE TITLE
Demasiadas clases en el diagrama de clases

### ISSUE THREAD

**Issue by dari1495** [Belberus/notas-vv#6]
El diagrama de clases no cumple el convenio que dice que sería recomendable no incluir entre más de 5 y 7 clases en un diagrama de clases para facilitar su legibilidad. 
Si es necesario, se pueden proporcionar diagramas de clases adicionales o mostrar algunas clases solo con el nombre de la clase si en algún otro diagrama ya se muestra su detalle de atributos y métodos.

**Comment by Belberus** [comment]
Por la arquitectura del sistema era necesario un diagrama con el número de clases actual. La restricción de 5 a 7 clases es sólo una recomendación.

**Comment by miguel-latre** [comment]
La arquitectura realmente no requiere que aparezcan 12 clases en el diagrama. Otra cosa es que, tal y como está, no se lea mal aunque no sigua esta recomendación, ni la del _issue_ #7 y no haga falta modificarlo.
